"""Added total_energy_kcal column

Revision ID: 62cd5834be43
Revises: 37c45c816734
Create Date: 2023-09-11 10:38:22.514028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cd5834be43'
down_revision = '37c45c816734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_nutrient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_energy_kcal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cholesterol', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_nutrient', schema=None) as batch_op:
        batch_op.drop_column('total_cholesterol')
        batch_op.drop_column('total_energy_kcal')

    # ### end Alembic commands ###
